//! RISC Zero prover backend.

use crate::benchmark::BenchmarkResult;
use crate::engine::{ProofOutput, ProvingEngine};
use anyhow::Result;
use std::time::Instant;

// Include the compiled guest methods (generated by risc0-build in build.rs).
// This provides constants like FIBONACCI_ELF and FIBONACCI_ID.
include!(concat!(env!("OUT_DIR"), "/methods.rs"));

/// RISC Zero proving engine using CPU prover.
pub struct Risc0Prover;

impl ProvingEngine for Risc0Prover {
    fn prove(&self, elf: &[u8], input_data: &[u8], po2: Option<u8>) -> Result<ProofOutput> {
        let start = Instant::now();

        let mut env_builder = risc0_zkvm::ExecutorEnv::builder();
        env_builder.write_slice(input_data);
        if let Some(po2) = po2 {
            if !(13..=24).contains(&po2) {
                anyhow::bail!("po2 value {po2} out of valid range 13..=24");
            }
            env_builder.segment_limit_po2(po2 as u32);
        }
        let env = env_builder
            .build()
            .map_err(|e| anyhow::anyhow!("Failed to build executor env: {e}"))?;

        let prover = risc0_zkvm::default_prover();
        let prove_info = prover
            .prove(env, elf)
            .map_err(|e| anyhow::anyhow!("RISC Zero proving failed: {e}"))?;

        let receipt = prove_info.receipt;
        let duration = start.elapsed();
        let cycles = prove_info.stats.total_cycles as u64;

        // Extract Groth16 seal for on-chain verification, fall back to
        // bincode-serialized receipt for off-chain/dev use.
        let seal = match receipt.inner.groth16() {
            Ok(groth16) => groth16.seal.clone(),
            Err(_) => {
                tracing::warn!("No Groth16 seal — proof not on-chain verifiable (dev/CPU mode)");
                bincode::serialize(&receipt.inner)
                    .map_err(|e| anyhow::anyhow!("Failed to serialize seal: {e}"))?
            }
        };

        Ok(ProofOutput {
            journal: receipt.journal.bytes.to_vec(),
            seal,
            duration,
            cycles,
        })
    }
}

/// Run a sha256-chain benchmark using the real RISC Zero prover.
pub fn benchmark_sha256_chain(n: u32) -> BenchmarkResult {
    tracing::info!("RISC Zero benchmark: sha256-chain({n})");
    let start = Instant::now();

    let input = n.to_le_bytes();
    let env = risc0_zkvm::ExecutorEnv::builder()
        .write_slice(&input)
        .build()
        .expect("Failed to build executor env");

    let prover = risc0_zkvm::default_prover();
    let prove_info = prover
        .prove(env, SHA256_CHAIN_ELF)
        .expect("RISC Zero sha256-chain proving failed");

    let duration = start.elapsed();
    let cycles = prove_info.stats.total_cycles as u64;
    let throughput = cycles as f64 / duration.as_secs_f64();

    tracing::info!(
        "  risc0 sha256-chain({n}): {cycles} cycles in {duration:?} ({throughput:.0} c/s)"
    );

    BenchmarkResult {
        program_name: format!("sha256-chain({n})"),
        prover_backend: "risc0".to_string(),
        cycles,
        duration,
        throughput,
        weight: 0.0,
        precompile: true,
    }
}

/// Run a fibonacci benchmark using the real RISC Zero prover.
pub fn benchmark_fibonacci(n: u32) -> BenchmarkResult {
    tracing::info!("RISC Zero benchmark: fibonacci({n})");
    let start = Instant::now();

    let input = n.to_le_bytes();
    let env = risc0_zkvm::ExecutorEnv::builder()
        .write_slice(&input)
        .build()
        .expect("Failed to build executor env");

    let prover = risc0_zkvm::default_prover();
    let prove_info = prover
        .prove(env, FIBONACCI_ELF)
        .expect("RISC Zero fibonacci proving failed");

    let duration = start.elapsed();
    let cycles = prove_info.stats.total_cycles as u64;
    let throughput = cycles as f64 / duration.as_secs_f64();

    tracing::info!("  risc0 fibonacci({n}): {cycles} cycles in {duration:?} ({throughput:.0} c/s)");

    BenchmarkResult {
        program_name: format!("fibonacci({n})"),
        prover_backend: "risc0".to_string(),
        cycles,
        duration,
        throughput,
        weight: 0.0,
        precompile: false,
    }
}
